// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhukegvicebiaopvgtzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZodWtlZ3ZpY2ViaWFvcHZndHp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjE4MzMsImV4cCI6MjA3MzY5NzgzM30.jWhh6KwO_nBI2RSNNtafJPhW4RIuiu3VDqGNq2V87_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== "undefined" ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});